<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Foundation\Auth\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            // Dev
            [
                'nama' => 'Raafi DEV',
                'username' => 'RaafiDEV',
                'email' => 'raafinakkeren16@gmail.com',
                'alamat' => 'Semarang Kota, Jawa Tengah',
                'no_ktp' => '1234567890123456',
                'no_hp' => '08123456789',
                'no_rm' => '',
                'id_poli' => '2',
                'role' => 'dokter',
                'password' => Hash::make('123')
            ],
            // Dokter
            [
                'nama' => 'Dr. Rudi Santoso, Sp.PD',
                'username' => 'rudi_santoso',
                'email' => 'rudi_santoso@example.com',
                'alamat' => 'Semarang Kota, Jawa Tengah',
                'no_ktp' => '1234567890123456',
                'no_hp' => '08123456789',
                'no_rm' => '',
                'id_poli' => '2',
                'role' => 'dokter',
                'password' => Hash::make('12345678')
            ],
            [
                'nama' => 'Dr. Anisa Farida, Sp.A',
                'username' => 'anisa_farida',
                'email' => 'anisa_farida@example.com',
                'alamat' => 'Semarang Kota, Jawa Tengah',
                'no_ktp' => '1234567890123456',
                'no_hp' => '08123456789',
                'no_rm' => '',
                'id_poli' => '1',
                'role' => 'dokter',
                'password' => Hash::make('12345678')
            ],
            [
                'nama' => 'Dr. Siti Rahmawati, Sp.OG',
                'username' => 'siti_rahmawati',
                'email' => 'siti_rahmawati@example.com',
                'alamat' => 'Semarang Kota, Jawa Tengah',
                'no_ktp' => '1234567890123456',
                'no_hp' => '08123456789',
                'no_rm' => '',
                'id_poli' => '4',
                'role' => 'dokter',
                'password' => Hash::make('12345678')
            ],
            [
                'nama' => 'Dr. Andi Wijaya, Sp.JP',
                'username' => 'andi_wijaya',
                'email' => 'andi_wijaya@example.com',
                'alamat' => 'Semarang Kota, Jawa Tengah',
                'no_ktp' => '1234567890123456',
                'no_hp' => '08123456789',
                'no_rm' => '',
                'id_poli' => '3',
                'role' => 'dokter',
                'password' => Hash::make('12345678')
            ],
            // Pasien
            [
                'nama' => 'Andi Prasetyo',
                'username' => 'andip',
                'email' => 'andi.prasetyo@example.com',
                'alamat' => 'Jakarta Selatan, DKI Jakarta',
                'no_ktp' => '3201011989010001',
                'no_hp' => '08123456001',
                'no_rm' => '12345-020',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Siti Nurhaliza',
                'username' => 'sitin',
                'email' => 'siti.nurhaliza@example.com',
                'alamat' => 'Yogyakarta, DI Yogyakarta',
                'no_ktp' => '3401021990010002',
                'no_hp' => '08123456002',
                'no_rm' => '12345-021',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Budi Santoso',
                'username' => 'budis',
                'email' => 'budi.santoso@example.com',
                'alamat' => 'Surabaya, Jawa Timur',
                'no_ktp' => '3571031992020003',
                'no_hp' => '08123456003',
                'no_rm' => '12345-022',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Dewi Lestari',
                'username' => 'dewiles',
                'email' => 'dewi.lestari@example.com',
                'alamat' => 'Bandung, Jawa Barat',
                'no_ktp' => '3271041993050004',
                'no_hp' => '08123456004',
                'no_rm' => '12345-023',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Rahmat Hidayat',
                'username' => 'rahmath',
                'email' => 'rahmat.hidayat@example.com',
                'alamat' => 'Medan, Sumatera Utara',
                'no_ktp' => '1271051994040005',
                'no_hp' => '08123456005',
                'no_rm' => '12345-024',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Fitriani Safitri',
                'username' => 'fitrianis',
                'email' => 'fitriani.safitri@example.com',
                'alamat' => 'Padang, Sumatera Barat',
                'no_ktp' => '1371061995050006',
                'no_hp' => '08123456006',
                'no_rm' => '12345-025',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Agus Salim',
                'username' => 'aguss',
                'email' => 'agus.salim@example.com',
                'alamat' => 'Malang, Jawa Timur',
                'no_ktp' => '3571071996060007',
                'no_hp' => '08123456007',
                'no_rm' => '12345-026',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Lina Marlina',
                'username' => 'linam',
                'email' => 'lina.marlina@example.com',
                'alamat' => 'Bekasi, Jawa Barat',
                'no_ktp' => '3271081997070008',
                'no_hp' => '08123456008',
                'no_rm' => '12345-027',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Hendra Wijaya',
                'username' => 'hendraw',
                'email' => 'hendra.wijaya@example.com',
                'alamat' => 'Tangerang, Banten',
                'no_ktp' => '3671091998080009',
                'no_hp' => '08123456009',
                'no_rm' => '12345-028',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Nurul Aini',
                'username' => 'nurula',
                'email' => 'nurul.aini@example.com',
                'alamat' => 'Semarang, Jawa Tengah',
                'no_ktp' => '3371101999090010',
                'no_hp' => '08123456010',
                'no_rm' => '12345-029',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Joko Widodo',
                'username' => 'jokow',
                'email' => 'joko.widodo@example.com',
                'alamat' => 'Solo, Jawa Tengah',
                'no_ktp' => '3371112000010011',
                'no_hp' => '08123456011',
                'no_rm' => '12345-030',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Mega Putri',
                'username' => 'megap',
                'email' => 'mega.putri@example.com',
                'alamat' => 'Bogor, Jawa Barat',
                'no_ktp' => '3271122001020012',
                'no_hp' => '08123456012',
                'no_rm' => '12345-031',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Ridwan Kamil',
                'username' => 'ridwank',
                'email' => 'ridwan.kamil@example.com',
                'alamat' => 'Bandung Barat, Jawa Barat',
                'no_ktp' => '3271132002030013',
                'no_hp' => '08123456013',
                'no_rm' => '12345-032',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Tiara Andini',
                'username' => 'tiaraa',
                'email' => 'tiara.andini@example.com',
                'alamat' => 'Palembang, Sumatera Selatan',
                'no_ktp' => '1671142003040014',
                'no_hp' => '08123456014',
                'no_rm' => '12345-033',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
            [
                'nama' => 'Fajar Nugroho',
                'username' => 'fajarn',
                'email' => 'fajar.nugroho@example.com',
                'alamat' => 'Balikpapan, Kalimantan Timur',
                'no_ktp' => '6471152004050015',
                'no_hp' => '08123456015',
                'no_rm' => '12345-034',
                'id_poli' => null,
                'role' => 'pasien',
                'password' => Hash::make('123'),
            ],
        ];

        foreach ($users as $user) {
            User::create($user);
        };
    }
}
